version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/tb_data.sql:/docker-entrypoint-initdb.d/tb_data.sql:ro

  web:
    build: .
    container_name: fastapi_web
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: mysql+mysqlconnector://${MYSQL_USER}:${MYSQL_PASSWORD}@db/${MYSQL_DATABASE}
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
    depends_on:
      - db

volumes:
  mysql_data: